/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/eS05xdGDi3d
 */
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import { Button } from '@/components/ui/button'

export type AudioPlayerProps = {
  src: string
  name: string
}

export function AudioPlayer({ src, name }: AudioPlayerProps): JSX.Element {
  return (
    <div className='grid gap-2'>
      <div className='rounded-xl overflow-hidden'>
        <audio className='w-full' controls src='/your-audio-file.mp3'>
          <track kind='captions' src={src} label='English' default />
        </audio>
      </div>
      <div className='py-2 grid gap-2'>
        <h1 className='text-xl font-semibold line-clamp-2'>{name}</h1>
      </div>
    </div>
  )
}
